version: '3.8'

services:
  app:
    build: .
    container_name: popflix-app
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/popflix?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_REDIS_HOST=redis
      - SPRING_MAIL_USERNAME=tjdns2849@gmail.com
      - SPRING_MAIL_PASSWORD=qnniuzgfxisoeif
      - TMDB_API_KEY=9c736f988da33c03c23aac22040cac02
      - AWS_ACCESS_KEY_ID=AKIAS66UDJHXWKOKISZN
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_REGION=ap-northeast-2
      - AWS_S3_BUCKET=my-spring-popflix-app-bucket
      - GOOGLE_CLIENT_ID=569044455676-298a3786vpf0ph8f762ifpvgdr0habj4.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - NAVER_CLIENT_ID=DoDkaWieoblYsz61VZtG
      - NAVER_CLIENT_SECRET=3H01HVuCGg
      - JWT_SECRET_KEY=your_very_long_and_very_secure_secret_key_that_is_at_least_512_bits_long_please_change_this_in_production

    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    container_name: popflix-db
    environment:
      - MYSQL_DATABASE=popflix
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - "3308:3306"    # 외부 포트를 3308로 변경
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:6.2
    container_name: popflix-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data: